language: python

python:
   - "3.5"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install numpy
    - pip install requests
    - pip install flask
    - pip install flask-Script
    - pip install flask-sqlalchemy
 
before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version

script:
    - date
    - ls -al 
    - make check
    - make test
