language: python

python:
   - "3.5"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install numpy
    - pip install requests
    - pip install flask

before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version

script:
    - date
    - make test
