language: python

python:
   - "3.5"

services:
    - mysql

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install numpy
    - pip install requests
    - pip install flask
    - pip install flask-Script
    - pip install flask-sqlalchemy
    - pip install gunicorn
    - pip install pymysql
    - pip install Flask-Testing
 
before_script:
    - uname -a
    - printenv
    - pip list
    - mysql -e 'create database dudecarryme;'
    - python app/app.py create_travis_db
    - coverage --version

script:
    - date
    - ls -al
    - make check
    - make test
