version: "2"

# A Docker Compose file for configuration of the development environment

services:
  # load balancer
  lb:
    extends:
      file: docker-compose-common.yml
      service: lb

  # app
  app:
    extends:
      file: docker-compose-common.yml
      service: app
    ports:
      # Publish the port so it's visible on the host, you can access the app directly
      - "8000:8000"
    volumes:
      # Mount the app dir in the container as /src so our changes to the app code
      # are also changed in the container
      - ./app:/src
      # environment:
      # Environment variables to configure the app on startup.
      # We dont care about commiting these creds to GitHub because theyre only
      # for our local development environment
      #- MYSQL_USER=guestbook-admin
      #- MYSQL_PASSWORD=my-guestbook-admin-password
    command: gunicorn --reload app:app --bind 0.0.0.0:8000
      # Run Gunicorn to serve app requests and reload on change so we can see our
      # changes to the app code

networks:
  backend: {}
